server:
  port: 8761

#  eureka实例的主机名
eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false   #不把自己注册到eureka上
    fetch-registry: false  #不从eureka上获取服务注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/  #注册中心地址
